#!/usr/bin/env python3
"""Merge per-variant fragments into assets/manifest.json (used by nightly CI).

Reads every frag/**/<variant>.json produced by gen_manifest_fragment.py across the
build matrix and writes a single assets/manifest.json that dpack consumes.

Env:
  REPO       owner/repo, e.g. Isaiah-WU/dpack
  VERSION    deepmd-kit version (default: read assets/version.txt)
"""
import glob
import json
import os

repo = os.environ.get("REPO", "Isaiah-WU/dpack")
version = os.environ.get("VERSION", "").strip()
if not version:
    with open("assets/version.txt") as fh:
        version = fh.read().strip()

variants = {}
for f in sorted(glob.glob("frag/**/*.json", recursive=True)):
    with open(f) as fh:
        frag = json.load(fh)
    variants[frag["variant"]] = frag["entry"]

if not variants:
    raise SystemExit("merge_manifest: no fragments found under frag/")

manifest = {
    "repository": f"https://github.com/{repo}",
    "manifest_url": f"https://raw.githubusercontent.com/{repo}/main/assets/manifest.json",
    "_comment": "Auto-generated by .github/workflows/nightly.yml. Do not edit by hand.",
    "tools": {
        "dp": {
            "name": "DeePMD-kit",
            "description": "Deep Potential Molecular Dynamics — neural network interatomic potential",
            "homepage": "https://github.com/deepmodeling/deepmd-kit",
            "version": version,
            "variants": variants,
        }
    },
}

with open("assets/manifest.json", "w") as fh:
    json.dump(manifest, fh, indent=2)
    fh.write("\n")
print(json.dumps(manifest, indent=2))
